JupiterOne/data-model

package.json
src/IntegrationSchema.ts
src/index.test.ts
src/schemas/Disk.json

Fixes #31 - Create Disk schema

---

CHANGELOG.md
package.json
src/schemas/Host.json

Fixes #29 - Remove requirement for hostname in Host

---

src/RelationshipClass.ts

Required for https://github.com/JupiterOne/graph-azure/issues/132
Also added some RelationshipClass docstrings.

Add DENIES relationship class

---

CHANGELOG.md
package.json
src/RelationshipClass.ts

Used in existing integrations such as gitlab (https://github.com/JupiterOne/graph-gitlab/blob/master/src/steps/build-user-approved-merge-request-relationships/index.ts#L87)

Add RelationshipClass.APPROVED

---

CHANGELOG.md
src/IntegrationSchema.ts
src/schemas/ThreatIntel.json

Please consider:
- Is the `description` sufficient for describing when to use this class instead of `Vulnerability`?
- Would `ThreatIntelligence` be a better name for this entity after all? The `description` I've got hear suggests so in my mind.
- What properties are missing? Take a look at `Finding` and `Vulnerability` and `Weakness`. Let's be sure these all make sense when considered together/in how they're related.
Here is an example use case we've seen:
```json
"properties": {
"qid": 10401,
"name": "AWOL Remote Arbitrary Code Execution Vulnerability",
"severity": 5,
"cvssBase": "7.5",
"cvssBaseV3": "",
"cvssTemporal": "6.2",
"cvssTemporalV3": "",
"diagnosis": "masked",
"consequence": "masked",
"rtiActiveAttack": "0.0",
"rtiDos": "0.0",
"rtiMalware": "0.0",
"rtiPrivEsc": "0.0", …
```

Add ThreatIntel entity

---

CHANGELOG.md
package.json
src/RelationshipClass.ts

See #66 for details. This class is currently referenced inside of the Jamf integration.

Fixes #66 - Add RelationshipClass.INSTALLED

---

src/schemas/Vendor.json
src/validateEntityWithSchema.test.ts

Hello @aiwilliams ! Per our discussion on Slack, this is a change to update the Vendor schema from a string type to an array of strings. Thanks!

Updated Vendor from type:string to string[]

---

CHANGELOG.md
src/IntegrationSchema.ts
src/schemas/Account.json
src/schemas/DataStore.json
src/schemas/IpAddress.json
src/schemas/Organization.json
src/validateEntityWithSchema.test.ts

This will actually validate properties declared as format "ip".

Fix missing ip format log messages

---

CHANGELOG.md
src/schemas/DataObject.json
src/validateEntityWithSchema.test.ts

First commit is a failing test. cc @eXtremeX

Fixes #90 - DataObject classification field should accept null

---

CHANGELOG.md
src/IntegrationSchema.ts
src/schemas/DataCollection.json
src/schemas/DataTable.json
src/validateEntityWithSchema.test.ts

Fixes #96 - Introduce `DataTable` entity class

---

CHANGELOG.md
package.json
src/RelationshipClass.ts

This is needed to convert the Knowbe4 integration to the new sdk.

Add completed relationship class

---

CHANGELOG.md
package.json
src/schemas/User.json

Fixes #111 - Add `firstName` and `lastName` properties to `User` entity class

---

CHANGELOG.md
package.json
src/RelationshipClass.ts

This is used in NPM. https://github.com/JupiterOne/graph-npm/blob/master/docs/jupiterone.md#L89

Add RelationshipClass.PUBLISHED

---

.gitignore
src/schemas/AccessRole.json

Please see https://github.com/JupiterOne/graph-google/pull/118 for description.

INT-1715: Ingest Google admin roles

---

CHANGELOG.md
src/RelationshipClass.ts

@ndowmon 
Small update in support of graph-aws.
Once it's merged, can you put out the new version of the SDK that uses this data-model update?

Adding RelationshipClass.LOGS

---

CHANGELOG.md
src/RelationshipClass.ts

@ndowmon 
Small update for graph-aws

Adding RelationshipClass.SENDS

---

CHANGELOG.md
src/RelationshipClass.ts

Adding this relationship class for the configservice spec in graph-aws

Add RelationshipClass.EVALUATES

---

CHANGELOG.md
src/RelationshipClass.ts

Adding RelationshipClass.RUNS for graph-aws ECS spec

Add RelaitonshipClass.RUNS

---

src/schemas/User.json

Adding a timestamp for when the user last rotated their password.

Updating User schema to include pw rotation field

---

src/schemas/Vendor.json

Updating the schema to include a timestamp of when it was last reviewed in accordance with the review timeframes stipulated in vendor management policies.

Update Vendor schema with timestamp of last review

---

CHANGELOG.md
package.json

Release 0.50.0

---

CHANGELOG.md
package.json
src/schemas/User.json

Updating the required properties for `User`.

update user required properties
